on:
  push:
    branches-ignore: [gh-pages]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  nimversion:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion: [stable, devel]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        nimversion: ${{ matrix.nimversion }}
    - run: nim -v
    - run: nimble -v
