on: [push]

env:
  VERSION_TO_TEST: '{{ "iffy/install-nim@" + github.ref }}'

jobs:
  nimversion:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion: [stable, devel]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: ${{ VERSION_TO_TEST }}
      with:
        nimversion: ${{ matrix.nimversion }}
    - run: nim -v
    - run: nimble -v
